### ISSUE TITLE
Not working with TLS 1.1

### ISSUE THREAD

**Issue by 2208Abhinav** [awslabs/awscli-plugin-tls#1] opened 2023-08-03 14:45 UTC
I am following the steps present in the README, the only change is I am specifying TLS version to be 1.1 instead of 1.2 as mentioned in the guide. But when I make the request, still TLS 1.2 is used.

My usecase is that I want to use aws cli with TLS 1.0 and TLS 1.1 for some testing purpose.

Below is the content of config file:
```
[default]
tls_version = 1.1

[plugins]
cli_legacy_path = ...
tls = awscli_plugin_tls
```

aws cli version is 2.13.6

EDIT:
I went through the code, it looks like only 1.2 and 1.3 is supported. Is there a way to extend this code to use 1.0 and 1.1?

**Comment by ryfestag** [comment] 2024-02-23 15:15
Sorry for the delay, I'm not sure why I didn't get a notification when this was posted. Thank you for taking the time to report this. 

The intent of this plugin is specifically to ensure increased security of connections by using secure TLS protocols only and also allowing you to configure cipher suites appropriate for your organization. TLS 1.0 and 1.1 are explicitly not included because they are deprecated (https://datatracker.ietf.org/doc/html/rfc8996) and considered insecure by design. As a result, we don't intend to add support for those protocols. We would strongly recommend against using them.

**Comment by ryfestag** [comment] 2024-02-23 15:16
Closing

**Closed as not planned by ryfestag** 2024-02-23 15:16 UTC
